### ISSUE TITLE
[Bug] 0: 下载图片 失败 1: builder error 2: relative URL without a base

### ISSUE THREAD

**Issue by Zzy-114514** [lanyeeee/bilibili-manga-downloader#10]
使用的过程中会频繁出现，下载图片失败的情况：
```
0: 下载图片 失败
1: builder error
2: relative URL without a base
```

**Comment by lanyeeee** [comment]
请提供复现步骤，是否已登录，出错的是哪部漫画，哪个章节，稳定出错还是偶发

**Comment by Zzy-114514** [comment]
> 请提供复现步骤，是否已登录，出错的是哪部漫画，哪个章节，稳定出错还是偶发

按照视频操作，已登录，频繁出现图片下载失败，只试了两本：
《猫之茗》有5章无法下载（6 24 39 48 68）
《为了美少女游戏，女装也是不可避免的》整本无法下载

**Comment by lanyeeee** [comment]
你用的是0.3版本吗，我这边下载《为了美少女游戏，女装也是不可避免的》是正常的

**Comment by Zzy-114514** [comment]
> 你用的是0.3版本吗，我这边下载《为了美少女游戏，女装也是不可避免的》是正常的

我又试了一遍，0.3版本是正常的，但0.4版本就不行了

**Comment by lanyeeee** [comment]
你用 0.3 版本能正常下载？你确定吗？是不是你弄混了
0.3 版本下载时应该每张图片都报如下错误才对
![image](https://github.com/user-attachments/assets/43230542-72a8-48cf-8b99-35ec2ca14559)

**Comment by Zzy-114514** [comment]
> 你用 0.3 版本能正常下载？你确定吗？是不是你弄混了
> 0.3 版本下载时应该每张图片都报如下错误才对
> ![image](https://github.com/user-attachments/assets/43230542-72a8-48cf-8b99-35ec2ca14559)
> ### 另外，你在网页或app能正常查看漫画吗？
> 

没有弄错，0.3可以正常下载可以编辑账号token，0.4无法正常下载仅支持扫码登录，我在网页和APP都可以正常阅读

**Comment by lanyeeee** [comment]
那估计是B漫在做灰度测试，你的账号还没被B漫那边切换到新版
0.3能正常使用吗？如果能就先用0.3吧，后续发现不能用了再升级到0.4就行
