### ISSUE TITLE
[功能请求] 请求添加下载图片后打包为CBZ功能

### ISSUE THREAD

**Issue by megamiNep** [lanyeeee/bilibili-manga-downloader#11]
### 原因

打包为CBZ后方便导入自建的漫画服务器进行整理和阅读

### 功能简述

将漫画图片与元数据打包至CBZ格式压缩包内

### 功能逻辑

在下载器设置中添加此选项

### 实现参考

Tachiyomi与其他哔哩哔哩漫画下载器均支持此功能，但最近其他下载器无法正常下载B站漫画了

**Comment by lanyeeee** [comment]
我漫画都是用电脑看，所以从来没有这种需求，对于这方面我并不了解
换句话说，我并不清楚到底要把漫画打包成什么样

下面是当前漫画目录的结构示意
```
📂 漫画名
├── 📂 第1章
│   ├── 001.jpg
│   ├── 002.jpg
│   └── 003.jpg
├── 📂 第2章
│   ├── 001.jpg
│   ├── 002.jpg
│   └── 003.jpg
└── 📂 第3章  
    ├── 001.jpg
    ├── 002.jpg
    └── 003.jpg
```

1. 如果要打包，这个目录结构会变成什么样，请仿照上面画一个新的示意图
2. 元数据要放在哪，元数据文件名是什么，是什么格式，内容是什么，请给出样例
3. 我猜应该要封面吧，封面放哪，封面文件名是什么
4. 最后是整个`漫画名`文件夹打包成`CBZ`压缩包吗？如果不是该如何打包，请具体说明

**Comment by a535813806** [comment]
感谢回复
1. 请允许我贴一个隔壁项目内此项功能提出并实现issues相关的链接：[https://github.com/Zeal-L/BiliBili-Manga-Downloader/pull/98#issue-2011329574](url)。
2. 此功能大致为将一个漫画章节的单话图片，打包为CBZ,例如：将漫画第一话、第二话，打包为第一话.cbz、第二话.cbz。
3. 每个cbz中都内含名为ComicInfo.xml的元数据文件，此文件可以被komga 和 kavita这类自建漫画网站识别读取。
4. ComicInfo.xml的内容样式我给出一个从Tachiyomi下载打包的cbz内的文件图片示例（手机码字请见谅），其中的<Title>🔒 42-42 <Title>，意为这是此漫画的第42话标题名称）。<Number>42</Number>（意为此章节的实际排序序号）
![Screenshot_2024-11-02-01-41-01-900_fit flutter dsm_helper-edit](https://github.com/user-attachments/assets/669745f8-b32e-4f08-8d0c-09415aedd6d2)
5. 具体文件结果如下，括号内为打包后样式
 📂 漫画名
├── 📂 第1章（.cbz）
│   ├── 001.jpg
│   ├── 002.jpg
│   └── 003.jpg
│   └──ComicInfo.xml
├── 📂 第2章（.cbz）
│   ├── 001.jpg
│   ├── 002.jpg
│   └── 003.jpg
│   └──ComicInfo.xml
6. cbz内无需特意指定封面，如cover.jpg。默认顺序第一张图片会作为此话封面。

**Comment by lanyeeee** [comment]
已在 [v0.6](https://github.com/lanyeeee/bilibili-manga-downloader/releases/tag/v0.6) 实现
