### ISSUE TITLE
[功能请求] 支持特典下载。

### ISSUE THREAD

**Issue by 9569856** [lanyeeee/bilibili-manga-downloader#12]
### 原因

进行保存整理，防止整改和谐。

### 功能简述

解析特典并下载。

### 功能逻辑

下载页面加一块位置列出。

### 实现参考

https://github.com/MOMOYATW/bilibili_manga_downloader
其目前可以查看特典解锁状态，但无法下载。

**Comment by lanyeeee** [comment]
我购买过的漫画里都不带特典，所以我没法实现这个功能

**Comment by lanyeeee** [comment]
刚才又翻了一下，还真让我翻出一个特典，之后会支持特典下载

**Comment by 9569856** [comment]
> 刚才又翻了一下，还真让我翻出一个特典，之后会支持特典下载

非常感谢了。

**Comment by lanyeeee** [comment]
已在[v0.5](https://github.com/lanyeeee/bilibili-manga-downloader/releases/tag/v0.5)完成
