### ISSUE TITLE
[Bug] 获取漫画详情失败 0: 获取漫画详情失败，将data解析为ComicRespData失败: 

### ISSUE THREAD

**Issue by caccac11** [lanyeeee/bilibili-manga-downloader#13]
### 问题描述

不清楚为什么其他漫画都可以成功提取图像数据并下载，但唯独"前列仙"却无法实现。

### 预期行为

可以提取"前列仙"及类似漫画的图像数据，以便正常下载。

### 实际行为

弹出了错误提示。

### 截图或录屏

扫描二维码登录之前的图像

![1](https://github.com/user-attachments/assets/7a9db6ba-b7fa-4ab8-a483-b7d39b0144ca)

扫描二维码登录后的图像

![Untitled](https://github.com/user-attachments/assets/f832a558-28d1-4eb7-b46e-44b2f535c7de)

错误代码详情

[获取漫画详情失败.txt](https://github.com/user-attachments/files/17604936/default.txt)

### 工具版本号

v0.4

**Comment by lanyeeee** [comment]
已在[v0.5](https://github.com/lanyeeee/bilibili-manga-downloader/releases/tag/v0.5)修复
