### ISSUE TITLE
[Bug] 大批量下载时，个别图片会下载失败

### ISSUE THREAD

**Issue by lanyeeee** [lanyeeee/bilibili-manga-downloader#17]
### 问题描述

在进行大批量下载时，部分章节的个别图片会下载失败，并报错`unexpected EOF during handshake`。
手动重新下载出错的章节可以解决问题。
复现条件：勾选《少女终末旅行》的所有章节，点击`下载勾选项`按钮，通常会有部分图片因该错误而未能成功下载。

### 预期行为

所有章节的图片应成功下载，不应出现`unexpected EOF during handshake`的错误。
即使出现错误，也不应该立即报错，应自动重试，重试多次后还失败才报错。

### 实际行为

部分章节的个别图片下载失败，并报错`unexpected EOF during handshake`。

### 截图或录屏

![image](https://github.com/user-attachments/assets/f0d7c49f-5afa-462b-aac7-4c8027d16bd7)

### 工具版本号

v0.5

### 其他

怀疑问题可能是由于当前的并发数过高导致请求被拒绝，当前代码在下载图片时缺少重试逻辑。
解决方案可以考虑降低并发数，并在下载图片时添加重试机制。

**Comment by kun4399** [comment]
同问题，能否添加设置最大并发下载数量的功能，避免同时下载漫画过多导致被判定为账号异常

**Comment by lanyeeee** [comment]
要`限制并发数`请另外开功能请求的issue

**Comment by lanyeeee** [comment]
已在 [v0.6](https://github.com/lanyeeee/bilibili-manga-downloader/releases/tag/v0.6) 修复
