### ISSUE TITLE
[Bug] 获取漫画详情遇到JSON解析错误

### ISSUE THREAD

**Issue by Water1573** [lanyeeee/bilibili-manga-downloader#2]
### 问题描述

一些漫画遇到无法获取的问题，一些漫画可以

### 预期行为

正常获取漫画信息

### 实际行为

无法获取信息

### 截图或录屏

![%~52DJJ3}OO%L@PWCPFGUTB](https://github.com/user-attachments/assets/c1c9cd52-abd8-43a9-bad6-7d71b1ce6b27)

### 工具版本号

V0.2

### 其他

因为想到一些漫画是境外的，所以打开VPN尝试（已经让电脑允许VPN使用，也能正常翻墙，排除VPN的问题），然后发现一些国内（如上图所示）也无法获取章节信息（由于没找到相关报错日志、运行日志导出的选项，仅能提供图片了T-T）,麻烦大佬了

**Comment by lanyeeee** [comment]
已在[v0.3](https://github.com/lanyeeee/bilibili-manga-downloader/releases/tag/v0.3)修复
