### ISSUE TITLE
[Bug] 特典很多的漫画无法正常显示正文章节

### ISSUE THREAD

**Issue by 3413185241** [lanyeeee/bilibili-manga-downloader#26]
### 问题描述

《这个勇者是金钱至上主义者》这部漫画只显示特典，没有显示出正文章节!

### 预期行为

应该显示出正文章节

### 实际行为

只显示出特典，没有正文章节

### 截图或录屏

![IMG_20241113_164512](https://github.com/user-attachments/assets/2270aef6-59ac-48e2-9944-01c0eabe946a)

### 工具版本号

0.6

**Comment by lanyeeee** [comment]
没想到有漫画能有这么多特典。。。

**Comment by lanyeeee** [comment]
已在 [v0.7](https://github.com/lanyeeee/bilibili-manga-downloader/releases/tag/v0.7) 修复
