### ISSUE TITLE
[Bug] 依旧会触发风控

### ISSUE THREAD

**Issue by chirs789eefs** [lanyeeee/bilibili-manga-downloader#31]
### 问题描述

下载10~20个章节后，账户会要求短信验证，继续操作之后会封禁30天。
客服给出的理由是"账号在多端登录"
b漫到底是防抓取还是防止多人共享账号，客服也没给个准确的说法。

### 预期行为

希望能解决一下触发风控的问题

### 实际行为

封禁30天，无法继续下载

### 工具版本号

v0.7

### 其他

无

**Comment by lanyeeee** [comment]
无法复现，我刚才又自己不限速同时下了几本漫画，总共十几G，也没能触发短信风控

你确定用的版本是0.7吗？你有重新扫码登录吗？

**Comment by lanyeeee** [comment]
经测试，此版本默认情况下确实仍会触发风控。不过风控后并没有封号。

之前我一直触发不了风控是因为我测试时使用的sessdata是从网页获取的，而扫码登录产生的sessdata会触发风控。

使用v0.7如果想要不触发风控，需要在扫码登录完成后，手动从网页获取sessdata，并替换`config.json`中的对应字段。
如果有人看不懂上面说的内容，我建议暂时不要使用，等待下一版本修复，一定要用请老老实实限制并发。

**Comment by lanyeeee** [comment]
已在 [v0.8](https://github.com/lanyeeee/bilibili-manga-downloader/releases/tag/v0.8) 修复
