### ISSUE TITLE
[Bug] 漫画中存在同名章节时，下载会报错 `系统找不到指定的路径。 (os error 3)`

### ISSUE THREAD

**Issue by lanyeeee** [lanyeeee/bilibili-manga-downloader#32]
### 问题描述

当漫画中存在同名章节时，下载会报错 `系统找不到指定的路径。 (os error 3)`。
看起来是由于在重命名文件夹时发生了错误。
复现条件：同时下载《其实我是最强的？》的多个番外篇。

### 预期行为

下载同名章节时应能正确处理文件夹命名。
当漫画中有同名章节时，应为每个章节生成唯一的文件夹，避免冲突。

### 实际行为

在下载多个名称相同的章节时，无法正确处理文件夹重命名，导致报错 `系统找不到指定的路径。 (os error 3)`，下载失败。

### 截图或录屏

![image](https://github.com/user-attachments/assets/000297dc-961a-4e2b-8d78-246c1b1efbe3)

### 工具版本号

v0.7

**Comment by ytyt-yt** [comment]
建议增加章节的编号保证文件夹顺序，也能解决章节同名问题。比如 [0001]xxx [0002]xyz

**Comment by lanyeeee** [comment]
已在 [v0.8](https://github.com/lanyeeee/bilibili-manga-downloader/releases/tag/v0.8) 修复
