### ISSUE TITLE
[功能请求] 能不能支持cookie登陆

### ISSUE THREAD

**Issue by Auroradanica** [lanyeeee/bilibili-manga-downloader#38]
### 原因

可以直接用网页端的cookie

### 功能简述

[功能请求] 能不能支持cookie登陆

### 功能逻辑

使用cookie进行登录

**Comment by lanyeeee** [comment]
已在 [v0.8](https://github.com/lanyeeee/bilibili-manga-downloader/releases/tag/v0.8) 完成
