### ISSUE TITLE
[Bug] 下载图片失败，`?token=`

### ISSUE THREAD

**Issue by NSun200512** [lanyeeee/bilibili-manga-downloader#6]
### 问题描述

漫画无法下载。

已经重新安装且重新登录，但仍无法解决这一问题。

### 预期行为

正常下载。

### 实际行为

弹出了错误提示。

### 截图或录屏

![6f2af654-2b0f-470d-be17-35fd683401e1](https://github.com/user-attachments/assets/9f2ff03e-c5fb-460d-94e6-c9e458d4b8d8)

### 工具版本号

v0.3

**Comment by lanyeeee** [comment]
我试了一下能正常下载啊
请给出问题的具体复现步骤
要下载哪部漫画，哪话才能出现这个问题

**Comment by f0banzai** [comment]
> 我试了一下能正常下载啊 请给出问题的具体复现步骤 要下载哪部漫画，哪话才能出现这个问题

例如义妹生活的18-23话。其它工具是需要在SESSDATA后面加上buvid3才能下载。

**Comment by lanyeeee** [comment]
这个情况看起来确实是没有`buvid3`。
但是要加上`buvid3`的问题已经在代码里自动完成了，可以看看配置文件(config.json)里有没有`buvid3`
如果有`buvid3`了还出现这个问题就很奇怪了

我刚才自掏腰包买了义妹生活21话，正常下载，我复现不了这个问题

![image](https://github.com/user-attachments/assets/3a1cc4ff-df65-4496-bb3d-58b73655d539)

![image](https://github.com/user-attachments/assets/0854a3a8-798f-4bcf-a2a7-07cbf54b4536)

**Comment by f0banzai** [comment]
> 这个情况看起来确实是没有`buvid3`。 但是要加上`buvid3`的问题已经在代码里自动完成了，可以看看配置文件(config.json)里有没有`buvid3` 如果有`buvid3`了还出现这个问题就很奇怪了
> 
> 我刚才自掏腰包买了义妹生活21话，正常下载，我复现不了这个问题
> 
> ![image](https://private-user-images.githubusercontent.com/73207840/381823790-3a1cc4ff-df65-4496-bb3d-58b73655d539.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNDk3NzQsIm5iZiI6MTczMDM0OTQ3NCwicGF0aCI6Ii83MzIwNzg0MC8zODE4MjM3OTAtM2ExY2M0ZmYtZGY2NS00NDk2LWJiM2QtNThiNzM2NTVkNTM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDA0Mzc1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyOGRhZWZlNThkYjAzMTc3YzA0Yzg3YTcwNzNkNDFkNDZkYWVjYjlkMjFhOWQzYTM2Y2JmNzUwMDJkYzc0OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WnF_MRGGVMjnOw1bumXsTLwegnEquM6nHulDodjPbWw)
> 
> ![image](https://private-user-images.githubusercontent.com/73207840/381824026-0854a3a8-798f-4bcf-a2a7-07cbf54b4536.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNDk3NzQsIm5iZiI6MTczMDM0OTQ3NCwicGF0aCI6Ii83MzIwNzg0MC8zODE4MjQwMjYtMDg1NGEzYTgtNzk4Zi00YmNmLWEyYTctMDdjYmY1NGI0NTM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDA0Mzc1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1M2E3MjY5ZjlhZjc5Y2M1YmUwZTJiMGUwNDZhODJiMmI1NTE3ZDUyZDQwNWY2NDAwZGI2NDk3NmI4NDRiNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YEB5H8pS2hSD9dC1hj65M3dRyz0vtLEpF_Yc1mFmiqU)

![QQ20241031-123706](https://github.com/user-attachments/assets/318ad199-1758-47a4-b561-5dfc08f0c0a6)
我这儿buvid3没问题，但也出现了和他一样的问题。很怪。但昨天，甚至昨天就是可以正常下载的。

**Comment by lanyeeee** [comment]
只有个别章节会这样，还是说几乎所有章节都这样？
网页和app能正常看漫画吗？
免费的章节能正常下载吗？
用其他下载器能正常下载吗？

**Comment by lanyeeee** [comment]
@f0banzai 我把你上一条评论删了，因为你SESSDATA没码干净

**Comment by f0banzai** [comment]
> 只有个别章节会这样，还是说几乎所有章节都这样？ 网页和app能正常看漫画吗？ 免费的章节能正常下载吗？ 用其他下载器能正常下载吗？

昨天下载成功的《[满级穿越的我为什么是牧师小姐啊](https://manga.bilibili.com/detail/mc34370)》刚才尝试下载其他章节就不行了。那么我目测就是几乎所有的都不行。网页（Edge 130）和安卓官方APP都能正常打开。免费章节也无法下载。其他下载器（https://github.com/MOMOYATW/bilibili_manga_downloader）目前可以下载。

**Comment by lanyeeee** [comment]
感谢你提供的信息
我知道问题是什么了，**是因为`buidv3`过期了，需要重新获取**
解决办法有两个
### 1. 把配置文件里`buidv3`的值改为`""`，即双引号内什么都不剩
保存`config.json`后重启软件，这样软件会因为缺少`buidv3`而自动重新获取新的
![image](https://github.com/user-attachments/assets/f9ced8f6-bab5-46a2-8590-d8cafa621887)

### 2 手动获取`buidv3`，然后更新到配置文件里，重启软件

之后有空了再改代码，改成每次启动软件都获取新的`buidv3`就行了

**Comment by lanyeeee** [comment]
B漫网页接口又变了，上面的解决方案也没用了
为了一劳永逸，计划把所有api都换成app的，工作量比较大，估计周末能完成

**Comment by lanyeeee** [comment]
已在[v0.4](https://github.com/lanyeeee/bilibili-manga-downloader/releases/tag/v0.4)修复
