### ISSUE TITLE
请问  解密图片那里  aes_cbc_decrypt 能改个语言么，python或者java都行，感谢

### ISSUE THREAD

**Issue by y657356105** [lanyeeee/bilibili-manga-downloader#69]
### 原因

不懂rust...

### 功能简述

想用python重现一下这个函数，不知如何做，看着像只用key，逐块16字节 解密，但是最开始的 iv因为是字符串不知具体怎么转成16位的byte?

### 功能逻辑

感谢

**Comment by y657356105** [comment]
urlString = 'https://mangaup.hdslb.com/bfs/manga/b9bb795e91f3767951535beb1a056b1a6a8d28c8.jpg@1100w.avif?cpx=AQAB28h%2Bz4WTO1tPwwPe1E47iRKOpg02pewziuiGgc9xJBplNDX93C9L50zsSCwAPPaAE6Rlemam2EzfEG0%2FJuyd6FpvSFW4IkH%2FfnRlRVKeJbcN1ucz8zRDW5iKcOabTf45QCLFC6hR%2F6bq7HKsMEjT23Pi2ORr%2Fb0CbhE3wXj%2BjsS9%2BeUp7Q23d3go8%2FiW%2B4FEtGDjSd%2BTL34h2Kny1oc%2F%2BnpS7V84GQQbg%2Bu7B%2F9pKEoBo3a0DHPQypj0%2B7og0ve2rUeWWLGfyg%3D%3D&token=d3346c86445dc2904f0906af506ddd16&ts=674b441c'

urlMessage = urlparse(urlString)
params = parse_qs(urlMessage.query)

cpx = params['cpx'][0]
iv = cpx[60:76]

with open(r'C:\Users\Administrator\Downloads\b9bb795e91f3767951535beb1a056b1a6a8d28c8.jpg@1100w (1).avif', 'rb') as f:
    fileData = f.read()
fileLen = fileData[1:5]

actualLen = int(b2a_hex(fileLen), 16)
actualFileData = fileData[5:actualLen + 5]
key = fileData[actualLen + 5:]

print(actualLen)
print(len(actualFileData))

iv = iv.encode('utf-8')
unpad = lambda s: s[0:-s[-1]]
cipher = AES.new(key, AES.MODE_CBC)

blockSize = 16
tempResultByteArray = b''

preBlock = iv
initHandleData = actualFileData[:20496]
index = 0
while True:
    index = index + 1
    print(index)
    singleBlock = initHandleData[:blockSize]
    newByteArray = []
    singleNewBlock = cipher.decrypt(singleBlock)
    for i in range(blockSize):
        newByteArray.append(singleNewBlock[i] ^ preBlock[i])

    tempResultByteArray = tempResultByteArray + bytes(newByteArray)
    print(b2a_hex(tempResultByteArray))
    initHandleData = initHandleData[blockSize:]
    if len(initHandleData) == 0:
        break

resultData = tempResultByteArray + actualFileData[20496:]


这个结果写入文件 不行

**Comment by lanyeeee** [comment]
https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#CBC

**Comment by lanyeeee** [comment]
我不想在特殊时期讨论这个
